// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WEB.Models;

namespace WEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180413104516_AddLink")]
    partial class AddLink
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEB.Models.Album", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ArtistId");

                    b.Property<string>("Cover");

                    b.Property<string>("NameAlbum");

                    b.Property<string>("NameArtist");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("WEB.Models.Artist", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Biography");

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("WEB.Models.Similar", b =>
                {
                    b.Property<Guid>("SimilarId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ArtistId");

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.HasKey("SimilarId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Similars");
                });

            modelBuilder.Entity("WEB.Models.Track", b =>
                {
                    b.Property<Guid>("TrackId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AlbumId");

                    b.Property<string>("Cover");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.HasKey("TrackId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("WEB.Models.Album", b =>
                {
                    b.HasOne("WEB.Models.Artist", "Artist")
                        .WithMany("Alb")
                        .HasForeignKey("ArtistId");
                });

            modelBuilder.Entity("WEB.Models.Similar", b =>
                {
                    b.HasOne("WEB.Models.Artist", "Artist")
                        .WithMany("Sim")
                        .HasForeignKey("ArtistId");
                });

            modelBuilder.Entity("WEB.Models.Track", b =>
                {
                    b.HasOne("WEB.Models.Album", "Album")
                        .WithMany("Music")
                        .HasForeignKey("AlbumId");
                });
#pragma warning restore 612, 618
        }
    }
}
